### ISSUE TITLE
dragItems : false not working 

### ISSUE THREAD

**Issue by drmatrix** [riktar/jkanban#112]
hi
im trying to give user permission about draggable items the "dragItems :" even set to false the items still draggable

**Comment by AEK-BKF** [comment]
Same here ! It doesn't work.
@drmatrix  please, did you find a solution ? Thanks

**Comment by marcosrocha85** [comment]
Are you using the property correctly? Are you using some event? Please uncomment dragItems at my fiddle and see it's actually working. https://jsfiddle.net/marcosrocha85/Lk9t483r/

**Comment by AEK-BKF** [comment]
@marcosrocha85  Thanks for quick reply,
I mean it doesn't work for a given board, not the whole jkanban.
Thanks

**Comment by marcosrocha85** [comment]
@AEK-BKF sure it has. Take a look at this fiddle:
```javascript
var kanban = new jKanban({
    element: '#myboard',
    dropEl: function(el, target, source, sibling) {
        // eg: if (["_todo","_cancel","_done"].indexOf(target.parentElement.dataset.id) == -1)
        if (!yourCoolValidationHere) {
            kanban.drake.cancel(true);
            return;
        }
    }
}
```
I made a table in database where I created the workflow for the boards (columns) and check if the target board is allowed to receive an item from source board. If cannot, I cancel the drake event and the item is not moved, otherwise I save the new column in database and update all cards sort order for target board.

**Comment by AEK-BKF** [comment]
@marcosrocha85 Thank you so much :))))
