### ISSUE TITLE
Add HTML form to the arbitrary position

### ISSUE THREAD

**Issue by bairog** [riktar/jkanban#149]
As I can see `addForm` function adds html element to the very bottom of the board. But can I add to the arbitrary position (for example between **1st** and **2nd** items)? Is there any workaround?

**Comment by marcosrocha85** [comment]
There are a couple of solutions here:
1. You can create a "temporary card" which has your HTML and set drake.cancel(true) at dragEl when user tries to drag it. Isn't so elegant but works; or
2. Use a library like [WebUI Popover](http://sandywalker.github.io/webui-popover/demo) in order to show a small popover allowing to user interact with your functions.

In a project of mine, I used addForm along with [jquery.scrollTo](http://demos.flesler.com/jquery/scrollTo/) in order to scroll user down when he/she clicked at "Add New". For fast editing actions I show a popover along some elements (User, Tags...). If user wants to edit full data, they click at card and I show a Dialog with all options.

**Comment by riktar** [comment]
Closed
