### ISSUE TITLE
Potential NPM error - Right click

### ISSUE THREAD

**Issue by MichaelBech** [riktar/jkanban#151]
First off, thank you for this great library.
I'm in the process of switching from downloading the files to installing via NPM.

The context event (Right-click) is not fired when using the NPM module.
But everything works flawless when using the downloaded files.
This could be a local setup issue, I dont know.
Do you have any pointers?

package.json:

"dependencies": {
        "@fortawesome/fontawesome-free": "^5.15.1",
        "bootstrap": "^4.5.3",
        "chart.js": "^3.6.2",
        "flatpickr": "^4.6.6",
        "jkanban": "^1.3.1",
        "jquery": "^3.5.1",
        "popper.js": "^1.16.1",
        "select2": "^4.0.13",
        "tinymce": "^5.6.0"
    },
    "devDependencies": {
        "@babel/cli": "^7.12.1",
        "@babel/core": "^7.12.3",
        "@babel/preset-env": "^7.12.1",
        "babel-loader": "^8.2.1",
        "css-loader": "^5.0.1",
        "mini-css-extract-plugin": "^1.3.1",
        "webpack": "^5.6.0",
        "webpack-cli": "^4.2.0"
    }

**Comment by marcosrocha85** [comment]
In order to use jkanban inside node_modules, you have to point out the same file you usually use when download. To be more clear, you have to use files from dist directory. If you're using webpack, laravel-mix or any other task automator, you have to tell it to copy node_modules/jkanban/dist/jkanban.min.js and node_modules/jkanban/dist/jkanban.min.css to your public folder.

**Comment by MichaelBech** [comment]
I see. Thank you for your input.
I will close the issue
