### ISSUE TITLE
Drag not working in mobile view

### ISSUE THREAD

**Issue by KeenthemesHub** [riktar/jkanban#80]
Hi,

Thanks for a great plugin. However, we had issue with board items in the mobile view. The board item cannot be moved and the page scrolls up and down when we drag it.

Our site here;
https://keenthemes.com/metronic/preview/demo1/components/extended/kanban-board.html

Our test video;
https://www.loom.com/share/794c3955d9114bbfb47973303f7f7677

Thanks

**Comment by marcosrocha85** [comment]
Wow, that's a very, very, VERY beaultiful job with jKanban. If I was @riktar I would be so proud.

Well, jKanban uses [Dragula](https://github.com/bevacqua/dragula) in order to make drag and drop possible and uses the latest version available (3.7.2). But, as far as I tested, it doesn't work with mobile devices very well yet.

Maybe you can integrate your Kanban with a javascript plugin like [DragDropTouch](https://github.com/Bernardo-Castilho/dragdroptouch).

**Comment by riktar** [comment]
similiar to #18 close
